sudo: false
language: java
jdk:
  - oraclejdk8
  - openjdk7

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-3/protoc-3.0.0-beta-3-linux-x86_64.zip
  - unzip protoc-3.0.0-beta-3-linux-x86_64.zip
  - export PROTOC_COMPILER="$(pwd)/protoc"

os:
  - linux

